package co.edu.icesi.demo.modelo;
// Generated 6/11/2016 08:36:05 PM by Hibernate Tools 5.1.0.Beta1

/**
 * CuentasRegistradas generated by hbm2java
 */
public class CuentasRegistradas implements java.io.Serializable {

	private long cueregCodigo;
	private Clientes clientes;
	private Cuentas cuentas;
	private String cueregDescripcion;

	public CuentasRegistradas() {
	}

	public CuentasRegistradas(long cueregCodigo, Clientes clientes, Cuentas cuentas, String cueregDescripcion) {
		this.cueregCodigo = cueregCodigo;
		this.clientes = clientes;
		this.cuentas = cuentas;
		this.cueregDescripcion = cueregDescripcion;
	}

	public long getCueregCodigo() {
		return this.cueregCodigo;
	}

	public void setCueregCodigo(long cueregCodigo) {
		this.cueregCodigo = cueregCodigo;
	}

	public Clientes getClientes() {
		return this.clientes;
	}

	public void setClientes(Clientes clientes) {
		this.clientes = clientes;
	}

	public Cuentas getCuentas() {
		return this.cuentas;
	}

	public void setCuentas(Cuentas cuentas) {
		this.cuentas = cuentas;
	}

	public String getCueregDescripcion() {
		return this.cueregDescripcion;
	}

	public void setCueregDescripcion(String cueregDescripcion) {
		this.cueregDescripcion = cueregDescripcion;
	}

}
