package co.edu.icesi.demo.modelo;
// Generated 16/08/2016 04:28:38 PM by Hibernate Tools 5.1.0.Beta1

import java.util.HashSet;
import java.util.Set;

/**
 * TiposDocumentos generated by hbm2java
 */
public class TiposDocumentos implements java.io.Serializable {

	private long tdocCodigo;
	private String tdocNombre;
	private Set<Clientes> clienteses = new HashSet<Clientes>(0);

	public TiposDocumentos() {
	}

	public TiposDocumentos(long tdocCodigo, String tdocNombre) {
		this.tdocCodigo = tdocCodigo;
		this.tdocNombre = tdocNombre;
	}

	public TiposDocumentos(long tdocCodigo, String tdocNombre, Set<Clientes> clienteses) {
		this.tdocCodigo = tdocCodigo;
		this.tdocNombre = tdocNombre;
		this.clienteses = clienteses;
	}

	public long getTdocCodigo() {
		return this.tdocCodigo;
	}

	public void setTdocCodigo(long tdocCodigo) {
		this.tdocCodigo = tdocCodigo;
	}

	public String getTdocNombre() {
		return this.tdocNombre;
	}

	public void setTdocNombre(String tdocNombre) {
		this.tdocNombre = tdocNombre;
	}

	public Set<Clientes> getClienteses() {
		return this.clienteses;
	}

	public void setClienteses(Set<Clientes> clienteses) {
		this.clienteses = clienteses;
	}

}
